// <auto-generated />
using System;
using BankManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SdgBank;

namespace BankManager.Migrations
{
  [DbContext(typeof(BankContext))]
  [Migration("20200225194909_AddedTables")]
  partial class AddedTables
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
          .HasAnnotation("ProductVersion", "3.1.2")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      modelBuilder.Entity("SdgBank.Account", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("AccountType")
                      .HasColumnType("text");

            b.Property<decimal>("Balance")
                      .HasColumnType("numeric");

            b.Property<string>("UserName")
                      .HasColumnType("text");

            b.Property<int>("User_ID")
                      .HasColumnType("integer");

            b.HasKey("ID");

            b.ToTable("Accounts");
          });

      modelBuilder.Entity("SdgBank.Transaction", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<string>("AccountType")
                      .HasColumnType("text");

            b.Property<int>("Account_ID")
                      .HasColumnType("integer");

            b.Property<decimal>("TransactionAmount")
                      .HasColumnType("numeric");

            b.Property<DateTime>("TransactionDate")
                      .HasColumnType("timestamp without time zone");

            b.Property<string>("TransactionType")
                      .HasColumnType("text");

            b.Property<string>("UserName")
                      .HasColumnType("text");

            b.HasKey("ID");

            b.ToTable("Transactions");
          });

      modelBuilder.Entity("SdgBank.User", b =>
          {
            b.Property<int>("ID")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer")
                      .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            b.Property<int>("AccountNumber")
                      .HasColumnType("integer");

            b.Property<string>("Password")
                      .HasColumnType("text");

            b.Property<string>("UserName")
                      .HasColumnType("text");

            b.HasKey("ID");

            b.ToTable("Users");
          });
#pragma warning restore 612, 618
    }
  }
}
